export const candidates = [
  {
    name: "VISHNU PACKRISAMY",
    image: "/candidates/grade12rep/vishnu.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/poster/vishnu.jpg",
    video: "",
  },
  {
    name: "SAMI KHAN",
    image: "/candidates/grade12rep/sami.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/poster/sami.jpg",
    video: "",
  },
  {
    name: "RYAN HUO",
    image: "/candidates/grade12rep/ryan.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/poster/ryan.jpg",
    video: "",
  },
  {
    name: "KHADIJA SAYVIDA",
    image: "/candidates/grade12rep/khadija.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/poster/khadija.jpg",
    video: "",
  },
  {
    name: "KASHAF RAO",
    image: "/candidates/grade12rep/kashaf.jpg",
    role: "grade 12 rep",  
    poster: "/candidates/grade12rep/poster/kashaf.jpg",
    video: "",
  },
  {
    name: "INESH HAQUE",
    image: "/candidates/grade12rep/inesh.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/poster/inesh.jpg",
    video: "",
  },
  {
    name: "ILHAM QADRI",
    image: "/candidates/grade12rep/ilham.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/poster/ilham.jpg",
    video: "",
  },
  {
    name: "HARRY LI",
    image: "/candidates/grade12rep/harry.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/poster/harry.jpg",
    video: "",
  },
  {
    name: "FAISAL MASAMRA",
    image: "/candidates/grade12rep/faisal.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/poster/faisal.jpg",
    video: "",
  },
  {
    name: "RAIMA HUSSAIN",
    image: "/candidates/grade11rep/raima.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/raima.jpg",
    video: "",
  },
  {
    name: "LEEN DWAIRI",
    image: "/candidates/grade11rep/leen.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/leen.jpg",
    video: "",
  },
  {
    name: "KARAN SAXENA",
    image: "/candidates/grade11rep/karan.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/karan.jpg",
    video: "",
  },
  {
    name: "KARAM ZAZA",
    image: "/candidates/grade11rep/karam.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/karam.jpg",
    video: "",
  },
  {
    name: "INAYA AFZAL",
    image: "/candidates/grade11rep/inaya.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/inaya.jpg",
    video: "",
  },
  {
    name: "FAARIS ZEESHAN",
    image: "/candidates/grade11rep/faaris.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/faaris.jpg",
    video: "",
  },
  {
    name: "ESHAAL CHEEMA",
    image: "/candidates/grade11rep/eshaal.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/eshaal.jpg",
    video: "",
  },
  {
    name: "DARSH SHAHDADPURI",
    image: "/candidates/grade11rep/urpicisglitched.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/darsh.jpg",
    video: "",
  },
  {
    name: "ASHAZ ARIF KHAN",
    image: "/candidates/grade11rep/ashaz.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/ashaz.jpg",
    video: "",
  },
  {
    name: "AMMAR ISANI",
    image: "/candidates/grade11rep/ammar.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/poster/ammar.jpg",
    video: "",
  },
  {
    name: "YOUSEF AL DABAGH",
    image: "/candidates/grade10rep/yousef.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/poster/yousef.jpg",
    video: "",
  },
  {
    name: "SAYON GHOSH",
    image: "/candidates/grade10rep/sayon.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/poster/sayon.jpg",
    video: "",
  },
  {
    name: "ROHAN PALADGU",
    image: "/candidates/grade10rep/rohan.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/poster/rohan.jpg",
    video: "",
  },
  {
    name: "RACHEL GIWA",
    image: "/candidates/grade10rep/rachel.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/poster/rachel.jpg",
    video: "",
  },
  {
    name: "KIRAT CHOPRA",
    image: "/candidates/grade10rep/kirat.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/poster/kirat.jpg",
    video: "",
  },
  {
    name: "JASON ZHAO",
    image: "/candidates/grade10rep/jason.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/poster/jason.jpg",
    video: "",
  },
  {
    name: "BAN AL-TEKREETI",
    image: "/candidates/grade10rep/ban.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/poster/ban.jpg",
    video: "",
  },
  {
    name: "ANANYA AHLUWALIA",
    image: "/candidates/grade10rep/ananya.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/poster/ananya.jpg",
    video: "",
  },
  {
    name: "AMINAH BUTT",
    image: "/candidates/grade10rep/aminah.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/poster/aminah.jpg",
    video: "",
  },
  {
    name: "YASHI SINGH",
    image: "/candidates/grade9rep/yashi.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/poster/yashi.jpg",
    video: "",
  },
  {
    name: "SURI NA",
    image: "/candidates/grade9rep/suri.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/poster/suri.jpg",
    video: "",
  },
  {
    name: "KAAVVYA WADEKAR",
    image: "/candidates/grade9rep/glitchedpic1.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/poster/kaavvya.jpg",
    video: "",
  },
  {
    name: "DORY HAIDER",
    image: "/candidates/grade9rep/dory.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/poster/dory.jpg",
    video: "",
  },
  {
    name: "BAANI CHANDI",
    image: "/candidates/grade9rep/glithcedpic2.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/poster/baani.jpg",
    video: "",
  },
];