export const candidates = [
  {
    name: "VISHNU PACKRISAMY",
    image: "/candidates/grade12rep/vishnu.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/posters/vishnu.jpg",
    video: "/candidates/grade12rep/video/vishnu.mp4",
  },
  {
    name: "SAMI KHAN",
    image: "/candidates/grade12rep/sami.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/posters/sami.pdf",
    video: "/candidates/grade12rep/video/sami.mp4",
  },
  {
    name: "RYAN HUO",
    image: "/candidates/grade12rep/ryan.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/posters/ryan.jpg",
    video: "/candidates/grade12rep/video/ryan.mp4",
  },
  {
    name: "KASHAF RAO",
    image: "/candidates/grade12rep/kashaf.jpg",
    role: "grade 12 rep",  
    poster: "/candidates/grade12rep/posters/kashaf.jpg",
    video: "/candidates/grade12rep/video/kashaf.mp4",
  },
  {
    name: "INESH HAQUE",
    image: "/candidates/grade12rep/inesh.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/posters/inesh.jpg",
    video: "/candidates/grade12rep/video/inesh.mp4",
  },
  {
    name: "ILHAM QADRI",
    image: "/candidates/grade12rep/ilham.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/posters/ilham.jpg",
    video: "/candidates/grade12rep/video/ilham.mp4",
  },
  {
    name: "HARRY LI",
    image: "/candidates/grade12rep/harry.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/posters/harry.jpg",
    video: "/candidates/grade12rep/video/harry.mp4",
  },
  {
    name: "FAISAL MASAMRA",
    image: "/candidates/grade12rep/faisal.jpg",
    role: "grade 12 rep",
    poster: "/candidates/grade12rep/posters/faisal.jpg",
    video: "/candidates/grade12rep/video/faisal.mp4",
  },
  {
    name: "RAIMA HUSSAIN",
    image: "/candidates/grade11rep/raima.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/raima.jpg",
    video: "/candidates/grade11rep/video/raima.mp4",
  },
  {
    name: "LEEN DWAIRI",
    image: "/candidates/grade11rep/leen.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/leen.jpg",
    video: "/candidates/grade11rep/video/leen.mp4",
  },
  {
    name: "KARAN SAXENA",
    image: "/candidates/grade11rep/karan.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/karan.jpg",
    video: "/candidates/grade11rep/video/karan.mp4",
  },
  {
    name: "KARAM ZAZA",
    image: "/candidates/grade11rep/karam.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/karam.jpg",
    video: "/candidates/grade11rep/video/karam.mp4",
  },
  {
    name: "INAYA AFZAL",
    image: "/candidates/grade11rep/inaya.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/inaya.jpg",
    video: "/candidates/grade11rep/video/inaya.mp4",
  },
  {
    name: "FAARIS ZEESHAN",
    image: "/candidates/grade11rep/faaris.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/faaris.jpg",
    video: "/candidates/grade11rep/video/faaris.mp4",
  },
  {
    name: "ESHAAL CHEEMA",
    image: "/candidates/grade11rep/eshaal.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/eshaal.jpg",
    video: "/candidates/grade11rep/video/eshaal.mp4",
  },
  {
    name: "DARSH SHAHDADPURI",
    image: "/candidates/grade11rep/urpicisglitched.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/darsh.jpg",
    video: "/candidates/grade11rep/video/darsh.mp4",
  },
  {
    name: "ASHAZ ARIF KHAN",
    image: "/candidates/grade11rep/ashaz.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/ashaz.jpg",
    video: "/candidates/grade11rep/video/ashaz.mp4",
  },
  {
    name: "AMMAR ISANI",
    image: "/candidates/grade11rep/ammar.jpg",
    role: "grade 11 rep",
    poster: "/candidates/grade11rep/posters/ammar.pdf",
    video: "/candidates/grade11rep/video/ammar.mp4",
  },
  {
    name: "YOUSEF AL DABAGH",
    image: "/candidates/grade10rep/yousef.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/posters/yousef.jpg",
    video: "/candidates/grade10rep/video/yousef.mp4",
  },
  {
    name: "SAYON GHOSH",
    image: "/candidates/grade10rep/sayon.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/posters/sayon.jpg",
    video: "/candidates/grade10rep/video/sayon.mp4",
  },
  {
    name: "ROHAN PALADGU",
    image: "/candidates/grade10rep/rohan.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/posters/rohan.jpg",
    video: "/candidates/grade10rep/video/rohan.mp4",
  },
  {
    name: "RACHEL GIWA",
    image: "/candidates/grade10rep/rachel.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/posters/rachel.jpg",
    video: "/candidates/grade10rep/video/rachel.mp4",
  },
  {
    name: "KIRAT CHOPRA",
    image: "/candidates/grade10rep/kirat.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/posters/kirat.jpg",
    video: "/candidates/grade10rep/video/kirat.mp4",
  },
  {
    name: "JASON ZHAO",
    image: "/candidates/grade10rep/jason.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/posters/jason.jpg",
    video: "/candidates/grade10rep/video/jason.mp4",
  },
  {
    name: "BAN AL-TEKREETI",
    image: "/candidates/grade10rep/ban.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/posters/ban.jpg",
    video: "/candidates/grade10rep/video/ban.mp4",
  },
  {
    name: "ANAYA AHLUWALIA",
    image: "/candidates/grade10rep/anaya.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/posters/anaya.jpg",
    video: "/candidates/grade10rep/video/anaya.mp4",
  },
  {
    name: "AMINAH BUTT",
    image: "/candidates/grade10rep/aminah.jpg",
    role: "grade 10 rep",
    poster: "/candidates/grade10rep/posters/aminah.jpg",
    video: "/candidates/grade10rep/video/aminah.mp4",
  },
  {
    name: "YASHI SINGH",
    image: "/candidates/grade9rep/yashi.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/posters/yashi.jpg",
    video: "/candidates/grade9rep/video/yashi.mp4",
  },
  {
    name: "SURI NA",
    image: "/candidates/grade9rep/suri.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/posters/suri.jpg",
    video: "/candidates/grade9rep/video/suri.mp4",
  },
  {
    name: "KAAVVYA WADEKAR",
    image: "/candidates/grade9rep/kaavvya.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/posters/kaavvya.jpg",
    video: "/candidates/grade9rep/video/kaavvya.mp4",
  },
  {
    name: "DORY HAIDER",
    image: "/candidates/grade9rep/dory.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/posters/dory.jpg",
    video: "/candidates/grade9rep/video/dory.mp4",
  },
  {
    name: "BAANI CHANDI",
    image: "/candidates/grade9rep/glithcedpic2.jpg",
    role: "grade 9 rep",
    poster: "/candidates/grade9rep/posters/baani.jpg",
    video: "/candidates/grade9rep/video/baani.mp4",
  },
];