export const candidates = [
  {
    name: "ARSHAAN THIND",
    image: "/candidates/president/arshaanthind.jpg",
    role: "president",
    poster: "/candidates/president/posters/arshaanthind.pdf",
    video: "",
  },
  {
    name: "SHAURYA DEDHIA",
    image: "/candidates/president/shauryadedhia.jpg",
    role: "president",
    poster: "/candidates/president/posters/shauryadedhia.pdf",
    video: "",
  },
  {
    name: "AMRITA R",
    image: "/candidates/vicepresident/amritar.jpg",
    role: "vice president",
    poster: "/candidates/vicepresident/posters/amritar.pdf",
    video: "",
  },
  {
    name: "ANANYA HASAN",
    image: "/candidates/vicepresident/ananyahasan.jpg",
    role: "vice president",
    poster: "/candidates/vicepresident/posters/ananyahasan.pdf",
    video: "",
  },
  {
    name: "RASLEEN KAUR",
    image: "/candidates/vicepresident/rasleenkaur.jpg",
    role: "vice president",
    poster: "/candidates/vicepresident/posters/rasleenkaur.pdf",
    video: "",
  },
  {
    name: "ABDELRAHMAN",
    image: "/candidates/treasurer/abdelrahman.jpg",
    role: "treasurer",
    poster: "/candidates/treasurer/posters/abdelrahman.pdf",
    video: "",
  },
  {
    name: "KIRAT CHOPRA",
    image: "/candidates/treasurer/kiratchopra.jpg",
    role: "treasurer",
    poster: "/candidates/treasurer/posters/kiratchopra.pdf",
    video: "",
  },
  {
    name: "NADINE MUGHAL",
    image: "/candidates/treasurer/nadinemughal.jpg",
    role: "treasurer",
    poster: "/candidates/treasurer/posters/nadinemughal.pdf",
    video: "",
  },
  {
    name: "CAYDEN JANJUA",
    image: "/candidates/socialconvenor/caydenjanjua.jpg",
    role: "social convenor",
    poster: "/candidates/socialconvenor/posters/caydenjanjua.pdf",
    video: "",
  },
  {
    name: "NAVYA SHRIVASTAVA",
    image: "/candidates/socialconvenor/navyashrivastava.jpg",
    role: "social convenor",
    poster: "/candidates/socialconvenor/posters/navyashrivastava.pdf",
    video: "",
  },
];
